title:             Stefan Glorch
email:             info@sglorch.de
description:
author:            Stefan Glorch
baseurl:           ""
url:               "https://sglorch.de"

# Social Profiles
twitter_username:
github_username:   sglorch
facebook_username:

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  #https://github.com/bdesham/reading_time
  - jekyll-gist #https://github.com/jekyll/jekyll-gist
  - jekyll-seo-tag #https://github.com/jekyll/jekyll-seo-tag
  #- jekyll-github-metadata
  - jekyll-target-blank
  - jekyll-sitemap
  - jekyll-minifier
  - jekyll-image-optim

sass:
  style: compressed

jekyll-minifier:
  preserve_php: true                # Default: false
  remove_spaces_inside_tags: true   # Default: true
  remove_multi_spaces: true         # Default: true
  remove_comments: true             # Default: true
  remove_intertag_spaces: true      # Default: false
  remove_quotes: false              # Default: false
  compress_css: true                # Default: true
  compress_javascript: true         # Default: true
  compress_json: true               # Default: true
  simple_doctype: false             # Default: false
  remove_script_attributes: false   # Default: false
  remove_style_attributes: false    # Default: false
  remove_link_attributes: false     # Default: false
  remove_form_attributes: false     # Default: false
  remove_input_attributes: false    # Default: false
  remove_javascript_protocol: false # Default: false
  remove_http_protocol: false       # Default: false
  remove_https_protocol: false      # Default: false
  preserve_line_breaks: false       # Default: false
  simple_boolean_attributes: false  # Default: false
  compress_js_templates: false      # Default: false
  preserve_patterns:                # Default: (empty)
  uglifier_args:                    # Default: (empty)

# image_optim-jekyll-plugin customizations.
image_optim:
  archive_dir: "assets/full-res-img"
  cache_file: "tmp/img-opt-cache.yml"
  image_glob: "img/**/*.{gif,png,jpg,jpeg}"
